# Site settings
title: "Mountain_blue Kim Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "POOREUMOE KIM, 김푸르뫼"
resume_title:                   "ML Engineer/Data scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kprm2000@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+4917-75964673"
resume_contact_address:         "Waagstrasse 2, Eching, Germany"

resume_header_contact_info:     "Waagstrasse 2, Eching, Germany  • kprm2000@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Network analysis, Time seires forecasting, NLP <br>I'm currently searching for a job in South Korea!. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
#resume_github_url:            "https://github.com/jglovier/resume-template"
# resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "www.linkedin.com/in/pooreumoe-kim-57632085"
  # resume_instagram_url:         "insert your Instagram URL here"
# resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@kprm2000"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
